### ISSUE TITLE
the calculation of covariance matrix in bic_single_gaus.py 

### ISSUE THREAD

**Issue by 1215thebqtic** [gdebayan/Diarization_BIC#1]
Hi,
I'm confused about the covariance matrix calculated in bic_single_gaus.py. Can I get the covariance matrix by simply using `covx = np.cov(x.T)`?  x.shape= (features, samples) e.g. (13, 199). Thank you!

**Comment by gdebayan** [comment]
Hey, Yes you can, However what we wanted to do is extend it from 13-D MFCCs to 512- Dimension embeddings(Another feature). The problem we were facing is was that while using np.cov(), the value was tending to zero.(was working fine for 13-d MFCCs, however for 512 dimensions was always tending to 0)(bunch of small numbers being multiplied 512 times--->0 in python), hence we had to modify the code accordingly. But yes the usual np.cov() works.

**Comment by gdebayan** [comment]
I used np.var(x,1)----> which basically gives the diagonal cov. matrix

Not sure about np.cov(), I think this returns a full covariance matrix(not too sure), however if you want a full covariance matrix, I suggest you use the sklearn GMM library( was using this before, however modeling as GMM was taking too long, so decided to stick with single Gaussian). Its a very effective tool, however it takes up a lot of time
http://scikit-learn.org/stable/modules/mixture.html
